apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: myapp
type: Opaque
stringData:
  mysql-root-password: "root_password_super_secret"
  mysql-database: "simasu_db"
  mysql-user: "simasu_user"
  mysql-password: "simasu_password_123"
