apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  namespace: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: yudhapakel/simasu-web:latest # Menggunakan image dari Docker Hub yang nanti di-push Anggota 1
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: web-config
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-password
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: myapp
spec:
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30080 # Biar gampang diakses via Minikube IP
  type: NodePort
